/*
CockroachDB Cloud API

This is an early access, experimental version of the Cloud API. The interface and output is subject to change, and there may be bugs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: 2022-03-31
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateSQLUserRequest struct for CreateSQLUserRequest
type CreateSQLUserRequest struct {
	Name string `json:"name"`
	Password string `json:"password"`
}

// NewCreateSQLUserRequest instantiates a new CreateSQLUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSQLUserRequest(name string, password string) *CreateSQLUserRequest {
	this := CreateSQLUserRequest{}
	this.Name = name
	this.Password = password
	return &this
}

// NewCreateSQLUserRequestWithDefaults instantiates a new CreateSQLUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSQLUserRequestWithDefaults() *CreateSQLUserRequest {
	this := CreateSQLUserRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSQLUserRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSQLUserRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSQLUserRequest) SetName(v string) {
	o.Name = v
}

// GetPassword returns the Password field value
func (o *CreateSQLUserRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreateSQLUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreateSQLUserRequest) SetPassword(v string) {
	o.Password = v
}

func (o CreateSQLUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableCreateSQLUserRequest struct {
	value *CreateSQLUserRequest
	isSet bool
}

func (v NullableCreateSQLUserRequest) Get() *CreateSQLUserRequest {
	return v.value
}

func (v *NullableCreateSQLUserRequest) Set(val *CreateSQLUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSQLUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSQLUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSQLUserRequest(val *CreateSQLUserRequest) *NullableCreateSQLUserRequest {
	return &NullableCreateSQLUserRequest{value: val, isSet: true}
}

func (v NullableCreateSQLUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSQLUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


