/*
CockroachDB Cloud API

This is an early access, experimental version of the Cloud API. The interface and output is subject to change, and there may be bugs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: 2022-03-31
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ccloud

import (
	"encoding/json"
)

// ListAllowlistEntriesResponse struct for ListAllowlistEntriesResponse
type ListAllowlistEntriesResponse struct {
	Allowlist   []AllowlistEntry          `json:"allowlist"`
	Propagating bool                      `json:"propagating"`
	Pagination  *KeysetPaginationResponse `json:"pagination,omitempty"`
}

// NewListAllowlistEntriesResponse instantiates a new ListAllowlistEntriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAllowlistEntriesResponse(allowlist []AllowlistEntry, propagating bool) *ListAllowlistEntriesResponse {
	this := ListAllowlistEntriesResponse{}
	this.Allowlist = allowlist
	this.Propagating = propagating
	return &this
}

// NewListAllowlistEntriesResponseWithDefaults instantiates a new ListAllowlistEntriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAllowlistEntriesResponseWithDefaults() *ListAllowlistEntriesResponse {
	this := ListAllowlistEntriesResponse{}
	return &this
}

// GetAllowlist returns the Allowlist field value
func (o *ListAllowlistEntriesResponse) GetAllowlist() []AllowlistEntry {
	if o == nil {
		var ret []AllowlistEntry
		return ret
	}

	return o.Allowlist
}

// GetAllowlistOk returns a tuple with the Allowlist field value
// and a boolean to check if the value has been set.
func (o *ListAllowlistEntriesResponse) GetAllowlistOk() ([]AllowlistEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Allowlist, true
}

// SetAllowlist sets field value
func (o *ListAllowlistEntriesResponse) SetAllowlist(v []AllowlistEntry) {
	o.Allowlist = v
}

// GetPropagating returns the Propagating field value
func (o *ListAllowlistEntriesResponse) GetPropagating() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Propagating
}

// GetPropagatingOk returns a tuple with the Propagating field value
// and a boolean to check if the value has been set.
func (o *ListAllowlistEntriesResponse) GetPropagatingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Propagating, true
}

// SetPropagating sets field value
func (o *ListAllowlistEntriesResponse) SetPropagating(v bool) {
	o.Propagating = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListAllowlistEntriesResponse) GetPagination() KeysetPaginationResponse {
	if o == nil || o.Pagination == nil {
		var ret KeysetPaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAllowlistEntriesResponse) GetPaginationOk() (*KeysetPaginationResponse, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListAllowlistEntriesResponse) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given KeysetPaginationResponse and assigns it to the Pagination field.
func (o *ListAllowlistEntriesResponse) SetPagination(v KeysetPaginationResponse) {
	o.Pagination = &v
}

func (o ListAllowlistEntriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["allowlist"] = o.Allowlist
	}
	if true {
		toSerialize["propagating"] = o.Propagating
	}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableListAllowlistEntriesResponse struct {
	value *ListAllowlistEntriesResponse
	isSet bool
}

func (v NullableListAllowlistEntriesResponse) Get() *ListAllowlistEntriesResponse {
	return v.value
}

func (v *NullableListAllowlistEntriesResponse) Set(val *ListAllowlistEntriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAllowlistEntriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAllowlistEntriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAllowlistEntriesResponse(val *ListAllowlistEntriesResponse) *NullableListAllowlistEntriesResponse {
	return &NullableListAllowlistEntriesResponse{value: val, isSet: true}
}

func (v NullableListAllowlistEntriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAllowlistEntriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
