/*
CockroachDB Cloud API

This is an early access, experimental version of the Cloud API. The interface and output is subject to change, and there may be bugs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: 2022-03-31
Contact: support@cockroachlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ClusterStatusType the model 'ClusterStatusType'
type ClusterStatusType string

// List of ClusterStatusType
const (
	CLUSTER_STATUS_UNSPECIFIED ClusterStatusType = "CLUSTER_STATUS_UNSPECIFIED"
	CRDB_MAJOR_UPGRADE_RUNNING ClusterStatusType = "CRDB_MAJOR_UPGRADE_RUNNING"
	CRDB_MAJOR_UPGRADE_FAILED ClusterStatusType = "CRDB_MAJOR_UPGRADE_FAILED"
	CRDB_MAJOR_ROLLBACK_RUNNING ClusterStatusType = "CRDB_MAJOR_ROLLBACK_RUNNING"
	CRDB_MAJOR_ROLLBACK_FAILED ClusterStatusType = "CRDB_MAJOR_ROLLBACK_FAILED"
	CRDB_PATCH_RUNNING ClusterStatusType = "CRDB_PATCH_RUNNING"
	CRDB_PATCH_FAILED ClusterStatusType = "CRDB_PATCH_FAILED"
	CRDB_SCALE_RUNNING ClusterStatusType = "CRDB_SCALE_RUNNING"
	CRDB_SCALE_FAILED ClusterStatusType = "CRDB_SCALE_FAILED"
	MAINTENANCE_RUNNING ClusterStatusType = "MAINTENANCE_RUNNING"
	CRDB_INSTANCE_UPDATE_RUNNING ClusterStatusType = "CRDB_INSTANCE_UPDATE_RUNNING"
	CRDB_INSTANCE_UPDATE_FAILED ClusterStatusType = "CRDB_INSTANCE_UPDATE_FAILED"
	CRDB_EDIT_CLUSTER_RUNNING ClusterStatusType = "CRDB_EDIT_CLUSTER_RUNNING"
	CRDB_EDIT_CLUSTER_FAILED ClusterStatusType = "CRDB_EDIT_CLUSTER_FAILED"
	CRDB_CMEK_OPERATION_RUNNING ClusterStatusType = "CRDB_CMEK_OPERATION_RUNNING"
	CRDB_CMEK_OPERATION_FAILED ClusterStatusType = "CRDB_CMEK_OPERATION_FAILED"
	TENANT_RESTORE_RUNNING ClusterStatusType = "TENANT_RESTORE_RUNNING"
	TENANT_RESTORE_FAILED ClusterStatusType = "TENANT_RESTORE_FAILED"
)

// All allowed values of ClusterStatusType enum
var AllowedClusterStatusTypeEnumValues = []ClusterStatusType{
	"CLUSTER_STATUS_UNSPECIFIED",
	"CRDB_MAJOR_UPGRADE_RUNNING",
	"CRDB_MAJOR_UPGRADE_FAILED",
	"CRDB_MAJOR_ROLLBACK_RUNNING",
	"CRDB_MAJOR_ROLLBACK_FAILED",
	"CRDB_PATCH_RUNNING",
	"CRDB_PATCH_FAILED",
	"CRDB_SCALE_RUNNING",
	"CRDB_SCALE_FAILED",
	"MAINTENANCE_RUNNING",
	"CRDB_INSTANCE_UPDATE_RUNNING",
	"CRDB_INSTANCE_UPDATE_FAILED",
	"CRDB_EDIT_CLUSTER_RUNNING",
	"CRDB_EDIT_CLUSTER_FAILED",
	"CRDB_CMEK_OPERATION_RUNNING",
	"CRDB_CMEK_OPERATION_FAILED",
	"TENANT_RESTORE_RUNNING",
	"TENANT_RESTORE_FAILED",
}

func (v *ClusterStatusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ClusterStatusType(value)
	for _, existing := range AllowedClusterStatusTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ClusterStatusType", value)
}

// NewClusterStatusTypeFromValue returns a pointer to a valid ClusterStatusType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewClusterStatusTypeFromValue(v string) (*ClusterStatusType, error) {
	ev := ClusterStatusType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ClusterStatusType: valid values are %v", v, AllowedClusterStatusTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ClusterStatusType) IsValid() bool {
	for _, existing := range AllowedClusterStatusTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ClusterStatusType value
func (v ClusterStatusType) Ptr() *ClusterStatusType {
	return &v
}

type NullableClusterStatusType struct {
	value *ClusterStatusType
	isSet bool
}

func (v NullableClusterStatusType) Get() *ClusterStatusType {
	return v.value
}

func (v *NullableClusterStatusType) Set(val *ClusterStatusType) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterStatusType) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterStatusType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterStatusType(val *ClusterStatusType) *NullableClusterStatusType {
	return &NullableClusterStatusType{value: val, isSet: true}
}

func (v NullableClusterStatusType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterStatusType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

